export const EErrors = {
  NOT_FOUND: 0,
  UNAUTHORIZED: 1,
  UNAUTHENTICATED: 2,
  STOCK_ERROR: 3,
  DUPLICATED: 4,
  EXTERNAL: 5,
  INVALID_CREDENTIALS: 6,
  TOKEN_ERROR: 7,
  CREDENTIALS_ERROR: 8
};
